app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
     resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#hwi_oauth_redirect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#    prefix:   /connect

#hwi_oauth_login:
#    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    # prefix:   /login

#auth0_login:
#    pattern: /auth0/callback

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"